# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Website name
title: Hugo Academic CV Theme
# Website URL
baseURL: 'https://akghani.github.io'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

build:
  writeStats: true
enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart
timeout: 600000

taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types
markup:
  _merge: deep
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep

# Provide footer configuration.
footer:
  enable: true
  # You can provide your custom footer template using this option.
  # Put your template in "layouts/partials" folder of your repo.
  template: footer.html
  # Show/hide navigation in the footer. Default is "true".
  navigation:
    enable: true
    # show custom menus in the footer
    customMenus: true
  # Show/hide "Contact Me" section in the footer. Default is "true".
  contactMe:
    enable: true
  # Show/hide credentials section in the footer. Default is "true".
  credentials:
    enable: true
