# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
theme: minimal
day_night: true
font: minimal
font_size: L

# SEO
site_type: Person
local_business_type: ''
org_name: ''
description: 'Personal website of Abdelkarim el Ghani'

# Header navigation bar
header:
  navbar:
    enable: true
    blox: "navbar"  # 👈 make sure this is here
    align: right
    fixed_to_top: true

    logo:
      text: "Abdelkarim el Ghani"      # Your name
      filename: "logo.png"             # Logo path (in assets/media/)
      alt: "Logo of Abdelkarim el Ghani"

    button:
      enable: true
      text: "Get Started"
      url: "https://hugoblox.com/templates/"

    show_theme_chooser: true
    show_search: true
    highlight_active_link: true
    show_translations: false

# Localization
date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features
highlight: true
highlight_languages:
  - r
  - python
  - latex
  - bash
math: false
diagram: false
privacy_pack: false

edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false

show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true

reading_time: true
section_pager: false
docs_section_pager: true
sharing: true

copyright_license:
  enable: true
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'

abstract_length: 135
plugins_js: []

# Avatar settings (for About widget)
avatar:
  gravatar: false
  shape: circle

# Publication settings
publications:
  date_format: January 2006
  citation_style: apa

# Project display
projects:
  post_view: 3
  publication_view: 3
  talk_view: 3

# Breadcrumbs
breadcrumb:
  page_types:
    book: true

# Comments (disabled here)
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''

# Search
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false

# CMS / NetlifyCMS integration
cms:
  branch: master
  local_backend: false

# Icon packs
icon:
  pack:
    ai: true
