# Quarto Website Configuration
project:
  type: website
  output-dir: docs
#  render:
#    - "*.qmd"
#  resources:
#    - _assets/
#    - images/  
    
  preview:
    port: 22227
    browser: true
    watch-inputs: true
    navigate: true

# Enable Markdown extensions
from: markdown+emoji

#title-meta: "Abdelkarim el Ghani"

website:
  title: "Abdelkarim el Ghani"
  favicon: /images/favicon-akg.png  # Favicon image
  image: /images/logo-akg.png
  open-graph: true
      
      
  search:
    location: navbar
    type: overlay  # Search type
  page-navigation: true  # Enable navigation links on pages
  back-to-top-navigation: true  # Show back-to-top button
#  margin-header: |
#    ![](/images/logo-akg.png)

  navbar:
    title: Abdelkarim el Ghani
    pinned: true
    logo: /images/logo-akg.png  # Navbar logo
    left:
      - text: Home
        href: index.qmd
        icon: house-fill
      - text: About Me
        href: about.qmd
        icon: person-arms-up
      - text: Projects
        href: projects.qmd
        icon: graph-up
        menu:  # Dropdown menu for Projects
          - text: Fairplay
            href: projects/fairplay/index.qmd
          - text: Rotterdam Gold
            href: projects/rotterdamgold/index.qmd
      - text: Resume
        href: resume.qmd
        icon: file-earmark-text-fill
    right: 
      - text: Resources
        href: resources.qmd
      - icon: linkedin
        href: https://linkedin.com
        target: _blank
      - icon: github
        href: https://github.com
        target: _blank
        
#  sidebar: 
#    - id: projects
#      title: Projects
#      style: docked
#      contents: 
#        - projects/fairplay/index.qmd
#        - projects/rotterdamgold/index.qmd

  page-footer:
    background: dark
    left: |
      © 2025 Abdelkarim el Ghani
    center: |
      [![](https://img.shields.io/badge/License-CC%20BY--ND%204.0-lightgrey.svg)](https://creativecommons.org/licenses/by-nd/4.0/)
    right: |
      <span class="faux-block">Build with {{< fa brands r-project >}} and [![Quarto](https://quarto.org/quarto.png){fig-alt="Quarto logo blue round circle with a cross within the circumference" width=65px}](https://quarto.org/){target="_blank"}</span>
    border: true

#  reader-mode: true  # Enable reader mode

format:
  html:
    fontsize: 1.1em  # Set font size
    theme:
      light:
        - zephyr
        - _assets/styles-elm-light.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
      dark:
        - _assets/zephyr-dark.scss
        - _assets/styles-elm-dark.scss
        - _assets/styles-elm-base.scss
        - _assets/colors.scss
    css:
      - _assets/panelset-extras.css
    highlight-style:
      light: _assets/syntax-elm-light.theme
      dark: _assets/syntax-elm-dark.theme

    title-block-banner: ""
    title-block-style: plain
    title-block-categories: false
    monofont:	"Fira Mono"
    monobackgroundcolor: "#f7f7f7"
    code-tools: false
    code-block-border-left: true
    code-link: true
    code-fold: show
    
    toc: false  # Disable table of contents
    smooth-scroll: true
#    page-layout: article
    anchor-sections: true
    include-in-header: 
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1">
#  pdf:
#    documentclass: scrreprt

lightbox: auto

execute:
  cache: false  # Disable cache
  freeze: auto  # Freeze execution when no changes detected

editor:
  render-on-save: true  # Automatically render on save

