project:
  type: website
  output-dir: docs

website:
  title: "Abdelkarim el Ghani"
  description: "Personal site of Abdelkarim el Ghani."
  open-graph: true
  cookie-consent:
    type: express
    style: interstitial
    palette: light
  search: 
    location: navbar
    type: overlay
  back-to-top-navigation: true
  navbar:
    background: '#cdffcd'
    search: true
    left:
      - text: Home
        href: index.qmd
        icon: house-fill
      - text: About Me
        href: about.qmd
        icon: person-arms-up
      - text: Projects
        href: projects.qmd  # Projects page (projects.qmd)
        icon: graph-up
    tools:
      - icon: github
        href: https://github.com/  # GitHub link
        #target: _blank
      - icon: linkedin
        href: https://linkedin.com  # LinkedIn link
        #target: _blank

  page-footer: 
    left: 
    - text: © 2025 - Abdelkarim el Ghani
    right: 
    - href: https://www.quarto.org
      text: Built with Quarto
format:
  html:
    fontsize: 20px
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    #code-link: true
    #code-fold: show
    #code-tools: true
    #code-block-bg: "lightblue"
    #code-block-border-left: "#31BAE9"
    highlight-style: nord
  #pdf: 
  #  documentclass: scrreprt
editor: visual



