---
title: ""
subtitle: "<br/><br/><br/><br/><br/>"
format:
  html: 
    linestretch: 1.7
    page-layout: article
toc: true
#title-block-banner: "images/background-pic.jpg"
#title-block-banner-color: "black"
title-block-banner-color: "rgba(255, 255, 255, 0.9)"
include-in-header:
  - text: |
      <style>
      #title-block-header.quarto-title-block.default .quarto-title-meta {
        color: rgba(255, 255, 255, 0.9);
      }
      .quarto-title-block .quarto-title-banner {
        height: 0; /* hide */
      }
      #title-block-header {
        background: 
          /* top, transparent black, faked with gradient */
          linear-gradient(
            rgba(0, 0, 0, 0.7),
            rgba(0, 0, 0, 0.7)
          ),
          /* bottom, image */ 
          url(images/profile_pic_convolve.jpg);
        background-size: cover;
        background-position-y: center;
        height: 450px;
        opacity: 0.7; /* image opacity, lower means lighter */
        z-index: -1;
      }
      </style>
---

```{r}
#| eval: false
#| echo: false

# Load magick pkg
library(magick)

# Read the original image
 profile_pic <- magick::image_read("images/profile_pic_akg.jpg")
 
 # Apply blur effect
 #blur_pic <- magick::image_blur(profile_pic, 10, 10)
 
 # Save the processed image
 #magick::image_write(blur_pic, path = "images/profile_pic_blur.jpg")
 
 convlv_pic <- profile_pic %>% 
   magick::image_convolve('Laplacian:15') %>%
   magick::image_negate()

magick::image_write(convlv_pic, path = "images/profile_pic_convolve.jpg")

```

<br></br>



**Abdelkarim el Ghani** is a Research Assistant at the [**Erasmus University Rotterdam**](https://www.eur.nl/){target="_blank"}. His expertise lies in:

-   Statistical data analysis
-   Neuroscience
-   Open science practices

He is highly skilled in [**R**](https://www.r-project.org/){target="_blank"} programming, data visualization, and managing large-scale research datasets.

Abdelkarim has extensive experience in both academic and clinical research environments. He has:

-   Contributed to international conferences
-   Authored scientific publications
-   Supported open science initiatives by sharing code and workflows on platforms like the Open Science Framework ([**OSF**](https://osf.io/){target="\"_blank"}).

His research interests include:

-   Neurodevelopment
-   Brain imaging
-   Statistical modeling of behavioral data

Driven by a passion for data-driven problem-solving, Abdelkarim aims to advance reproducible and transparent scientific research.

<a href="https://www.pexels.com/photo/white-painted-wall-1939485/" target="_blank" class="small-link">Photo by Henry & Co.</a>
