---
title: "Abdelkarim el Ghani<br/>"
subtitle: "<br/>Data Analyst | Neuroscientist<br/><br/><br/>"
format: html
toc: true
title-block-banner: "images/block-banner.jpeg"
title-block-banner-color: "white"
title-block-categories: true
page-layout: article
---



::: {.g-col-12 .g-col-md-6}
**Welcome to My Portfolio!**\
I’m a statistical data analyst specializing in uncovering meaningful insights from complex datasets. My work lies at the intersection of neuroscience and data science, with a focus on statistical modeling, data visualization, and managing large-scale research initiatives.

With expertise in analyzing neurodevelopmental data and driving reproducible research, I aim to support data-driven solutions that enhance our understanding of human behavior and scientific processes.

To dive into the projects I’ve worked on, visit my [**Projects**](projects.qmd) page, where you’ll find detailed insights into the work I’ve done, ranging from statistical modeling to data visualization.

If you'd like to know more about my background, skills, and experience, check out the [**About Me**](about.qmd) page.

Let’s connect and explore how statistical analysis can contribute to impactful research and informed decision-making.
:::
